name: curtains_demo
description: >
  Demonstration of elevated, instant, and animated Curtains
  + some features from package Shadows.
version: 1.0.3+4
repository: https://github.com/Zabadam/curtains/tree/main/example
issue_tracker: https://github.com/Zabadam/curtains/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^2.0.0
  curtains:
    path: ../

flutter:
  uses-material-design: true
