name: curtains
description: Wrap a scrollable with scrim Curtains while not at the start or end, alluding to unrevealed content.
version: 0.9.0
author: Adam Skelton (Zabadam)
repository: https://github.com/Zabadam/curtains
issue_tracker: https://github.com/Zabadam/curtains/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
