name: curtains
description: >
  Super simple scrim Curtains, or shadow decorations, by wrapping
  a scrollable child, alluding to unrevealed content while not at
  the start or end.
version: 0.10.0
repository: https://github.com/Zabadam/curtains
issue_tracker: https://github.com/Zabadam/curtains/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shadows: ^0.9.0

dev_dependencies:
  very_good_analysis: ^2.0.0

flutter:
